# Thank you to the zls authors for this eaasy to understand release workflow for Zig.
# https://github.com/zigtools/zls/blob/master/.github/workflows/main.yml
name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig version
      - run: zig env

      - name: Build
        run: zig build

      - name: Run Tests
        run: zig build test

      - name: Build artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          declare -a targets=("x86_64-windows" "x86_64-linux" "x86_64-macos" "aarch64-linux" "aarch64-macos")
          mkdir -p "artifacts/"

          for target in "${targets[@]}"; do
            mkdir -p artifacts/$target
            echo "Building target ${target}..."   
            echo "Building safe"
            zig build -Dtarget=${target} -Doptimize=ReleaseSafe --prefix artifacts/${target}/
            cp LICENSE.md artifacts/${target}/
            zip -rj artifacts/cue2gdi-${target}.zip artifacts/${target}/*
          done
          
      - name: Release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/cue2gdi-x86_64-windows.zip
            artifacts/cue2gdi-x86_64-linux.zip
            artifacts/cue2gdi-x86_64-macos.zip
            artifacts/cue2gdi-aarch64-linux.zip
            artifacts/cue2gdi-aarch64-macos.zip
